# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-28 07:43
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateField(verbose_name='начало акции')),
                ('end', models.DateField(verbose_name='завершение акции')),
                ('premium', models.DateField(blank=True, null=True, verbose_name='дата завершения премиум-статуса')),
                ('text', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='текст')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.Company', verbose_name='компания')),
            ],
            options={
                'verbose_name': 'акция',
                'ordering': ('-premium', '-start'),
                'verbose_name_plural': 'акции',
            },
        ),
    ]
