# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-28 07:43
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('news', 'новости'), ('interview', 'интервью'), ('articles', 'статьи')], default='news', max_length=16, verbose_name='категория')),
                ('title', models.CharField(max_length=128, verbose_name='заголовок')),
                ('text', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='текст')),
                ('pub_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='время публикации')),
                ('is_chosen', models.BooleanField(default=False, verbose_name='избранная')),
            ],
            options={
                'verbose_name': 'публикация',
                'ordering': ['-pub_date'],
                'verbose_name_plural': 'публикации',
            },
        ),
        migrations.CreateModel(
            name='EntryDraft',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_modified', models.DateTimeField(auto_now=True, verbose_name='отредактировано')),
                ('is_ready', models.BooleanField(default=True, verbose_name='готово для размещения')),
                ('is_published', models.BooleanField(default=False, verbose_name='опубликовано')),
                ('category', models.CharField(choices=[('news', 'новости'), ('interview', 'интервью'), ('articles', 'статьи')], default='news', max_length=16, verbose_name='категория')),
                ('title', models.CharField(max_length=128, verbose_name='заголовок')),
                ('text', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='текст')),
                ('pub_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='время публикации')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='companies.Company', verbose_name='компания')),
            ],
            options={
                'verbose_name': 'черновик',
                'ordering': ('is_published', 'last_modified'),
                'verbose_name_plural': 'черновики',
            },
        ),
    ]
