# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-01 12:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0002_auto_20170228_1043'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entrydraft',
            options={'ordering': ('is_published', '-is_ready', 'last_modified'), 'verbose_name': 'черновик', 'verbose_name_plural': 'черновики'},
        ),
    ]
