# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-04 01:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0003_auto_20170301_1539'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='is_anonymously',
            field=models.BooleanField(default=False, verbose_name='анонимно'),
        ),
        migrations.AddField(
            model_name='entrydraft',
            name='is_anonymously',
            field=models.BooleanField(default=False, verbose_name='анонимно'),
        ),
    ]
