# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-04 04:37
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0004_auto_20170304_0410'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entrydraft',
            options={'ordering': ('is_published', '-is_ready', '-pub_date'), 'verbose_name': 'черновик', 'verbose_name_plural': 'черновики'},
        ),
        migrations.AlterField(
            model_name='entry',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='создатель публикации'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='is_anonymously',
            field=models.BooleanField(default=False, verbose_name='анонимная публикация'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='pub_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='время публикации'),
        ),
        migrations.AlterField(
            model_name='entrydraft',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='создатель черновика'),
        ),
        migrations.AlterField(
            model_name='entrydraft',
            name='is_anonymously',
            field=models.BooleanField(default=False, verbose_name='анонимная публикация'),
        ),
        migrations.AlterField(
            model_name='entrydraft',
            name='pub_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='время публикации'),
        ),
    ]
