# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-05 01:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0006_auto_20170304_0808'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entrydraft',
            name='last_modified',
        ),
    ]
