# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-11 15:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0008_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'категория публикаций', 'verbose_name_plural': 'категории публикаций'},
        ),
    ]
