# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-27 04:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0014_auto_20170615_1848'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='image',
            field=models.ImageField(blank=True, upload_to='entries/pub/%Y/%m/%d/', verbose_name='обложка'),
        ),
        migrations.AlterField(
            model_name='entrydraft',
            name='image',
            field=models.ImageField(blank=True, upload_to='entries/sug/%Y/%m/%d/', verbose_name='обложка'),
        ),
    ]
