# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-28 07:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SideBanner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_pages', models.CharField(choices=[('none', 'не выбраны'), ('all', 'все страницы'), ('not_main', 'кроме главной'), ('main', 'главная страница'), ('entries', 'публикации'), ('companies', 'компании'), ('persons', 'люди'), ('discounts', 'акции'), ('custom', 'произвольные страницы')], default='none', max_length=16, verbose_name='страницы показа')),
                ('name', models.CharField(max_length=128, verbose_name='наименование баннера')),
                ('code', models.TextField(verbose_name='код баннера')),
                ('image', models.ImageField(blank=True, upload_to='banners/%Y/%m/%d/', verbose_name='изображение')),
                ('start', models.DateField(blank=True, null=True, verbose_name='начало показа')),
                ('end', models.DateField(blank=True, null=True, verbose_name='завершение показа')),
            ],
            options={
                'verbose_name': 'боковой баннер',
                'verbose_name_plural': 'боковые баннеры',
            },
        ),
        migrations.CreateModel(
            name='TopBanner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_pages', models.CharField(choices=[('none', 'не выбраны'), ('all', 'все страницы'), ('not_main', 'кроме главной'), ('main', 'главная страница'), ('entries', 'публикации'), ('companies', 'компании'), ('persons', 'люди'), ('discounts', 'акции'), ('custom', 'произвольные страницы')], default='none', max_length=16, verbose_name='страницы показа')),
                ('name', models.CharField(max_length=128, verbose_name='наименование баннера')),
                ('code', models.TextField(verbose_name='код баннера')),
                ('image', models.ImageField(blank=True, upload_to='banners/%Y/%m/%d/', verbose_name='изображение')),
                ('start', models.DateField(blank=True, null=True, verbose_name='начало показа')),
                ('end', models.DateField(blank=True, null=True, verbose_name='завершение показа')),
            ],
            options={
                'verbose_name': 'верхний баннер',
                'verbose_name_plural': 'верхние баннеры',
            },
        ),
    ]
