# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-28 07:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
        ('banners', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='topbanner',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.Company', verbose_name='компания'),
        ),
        migrations.AddField(
            model_name='sidebanner',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.Company', verbose_name='компания'),
        ),
        migrations.AddField(
            model_name='sidebanner',
            name='right_banner',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='left_banner', to='banners.SideBanner', verbose_name='правый баннер'),
        ),
    ]
