# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-01 12:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banners', '0002_auto_20170228_1043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sidebanner',
            name='image',
            field=models.ImageField(blank=True, upload_to='banners/side/%Y/%m/%d/', verbose_name='изображение'),
        ),
        migrations.AlterField(
            model_name='topbanner',
            name='image',
            field=models.ImageField(blank=True, upload_to='banners/top/%Y/%m/%d/', verbose_name='изображение'),
        ),
    ]
