# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-15 14:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_auto_20170515_1714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custompage',
            name='title',
            field=models.CharField(max_length=384, verbose_name='заголовок'),
        ),
    ]
