# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-28 07:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(max_length=128, verbose_name='ответ')),
            ],
            options={
                'verbose_name': 'вариант',
                'verbose_name_plural': 'варианты',
            },
        ),
        migrations.CreateModel(
            name='Poll',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=128, verbose_name='вопрос')),
                ('finish', models.DateTimeField(verbose_name='завершение опроса')),
            ],
            options={
                'verbose_name': 'опрос',
                'verbose_name_plural': 'опросы',
            },
        ),
    ]
