# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-28 07:43
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.conf import settings
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import users.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('last_name', models.CharField(blank=True, max_length=30, verbose_name='фамилия')),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='имя')),
                ('patronymic', models.CharField(blank=True, max_length=30, verbose_name='отчество')),
                ('text', ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='о себе')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='дата рождения')),
                ('username', models.CharField(error_messages={'unique': 'Пользователь с таким именем уже существует.'}, help_text='Обязательное поле. Не более 150 символов. Только буквы, цифры и символы @/./+/-/_.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='имя пользователя')),
                ('image', models.ImageField(blank=True, upload_to='users/pub/%Y/%m/%d/', verbose_name='фотография')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='дата регистрации')),
                ('is_active', models.BooleanField(default=True, help_text='Отметьте, если пользователь должен считаться активным. Уберите эту отметку вместо удаления учётной записи.', verbose_name='активный')),
                ('is_staff', models.BooleanField(default=False, help_text='Отметьте,            если пользователь может входить в административную часть сайта.', verbose_name='статус персонала')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'профиль пользователя',
                'ordering': ('last_name', 'first_name', 'patronymic'),
                'verbose_name_plural': 'профили пользователей',
            },
            managers=[
                ('objects', users.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='UserDraft',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_modified', models.DateTimeField(auto_now=True, verbose_name='отредактировано')),
                ('is_ready', models.BooleanField(default=True, verbose_name='готово для размещения')),
                ('is_published', models.BooleanField(default=False, verbose_name='опубликовано')),
                ('last_name', models.CharField(blank=True, max_length=30, verbose_name='фамилия')),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='имя')),
                ('patronymic', models.CharField(blank=True, max_length=30, verbose_name='отчество')),
                ('text', ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='о себе')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='дата рождения')),
                ('image', models.ImageField(blank=True, upload_to='users/sug/%Y/%m/%d/', verbose_name='фотография')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='профиль')),
            ],
            options={
                'verbose_name': 'черновик профиля',
                'ordering': ('is_published', 'last_modified'),
                'verbose_name_plural': 'черновики профилей',
            },
        ),
    ]
