# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-28 07:43
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='название')),
                ('text', ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='о компании')),
                ('web_site', models.URLField(blank=True, max_length=128, verbose_name='сайт компании')),
                ('actual_address', models.CharField(blank=True, max_length=128, null=True, verbose_name='фактический адрес')),
                ('legal_address', models.CharField(blank=True, help_text='заполняется, если отличается от фактического.', max_length=128, null=True, verbose_name='юридический адрес')),
                ('image', models.ImageField(blank=True, upload_to='companies/pub/%Y/%m/%d/', verbose_name='логотип')),
                ('employees_number', models.PositiveSmallIntegerField(choices=[(0, 'не указано'), (1, 'от 1 до 5'), (2, 'от 5 до 10'), (3, 'от 10 до 50'), (4, 'от 50 до 100'), (5, 'от 100 до 500'), (6, 'от 500 до 1 000'), (7, 'от 1 000 до 5 000'), (8, 'от 5 000 до 10 000'), (9, 'более 10 000')], default=0, verbose_name='число сотрудников')),
                ('premium', models.DateField(blank=True, null=True, verbose_name='дата завершения премиум-статуса')),
            ],
            options={
                'verbose_name': 'профиль компании',
                'ordering': ('name',),
                'verbose_name_plural': 'профили компаний',
            },
        ),
        migrations.CreateModel(
            name='CompanyDraft',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_modified', models.DateTimeField(auto_now=True, verbose_name='отредактировано')),
                ('is_ready', models.BooleanField(default=True, verbose_name='готово для размещения')),
                ('is_published', models.BooleanField(default=False, verbose_name='опубликовано')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='название')),
                ('text', ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='о компании')),
                ('web_site', models.URLField(blank=True, max_length=128, verbose_name='сайт компании')),
                ('actual_address', models.CharField(blank=True, max_length=128, null=True, verbose_name='фактический адрес')),
                ('legal_address', models.CharField(blank=True, help_text='заполняется, если отличается от фактического.', max_length=128, null=True, verbose_name='юридический адрес')),
                ('image', models.ImageField(blank=True, upload_to='companies/sug/%Y/%m/%d/', verbose_name='логотип')),
                ('company', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='companies.Company', verbose_name='профиль')),
            ],
            options={
                'verbose_name': 'черновик профиля',
                'ordering': ('is_published', 'last_modified'),
                'verbose_name_plural': 'черновики профилей',
            },
        ),
        migrations.CreateModel(
            name='PubCompContact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=128, verbose_name='описание')),
                ('call_name', models.CharField(blank=True, max_length=128, verbose_name='обращение')),
                ('phone', models.CharField(blank=True, max_length=128, verbose_name='телефон')),
                ('email', models.EmailField(blank=True, max_length=128, verbose_name='электронная почта')),
                ('position', models.SmallIntegerField(blank=True, null=True, verbose_name='позиция')),
                ('pub_company_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='companies.Company')),
            ],
            options={
                'verbose_name': 'контакт',
                'ordering': ('position',),
                'verbose_name_plural': 'контакты',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SugCompContact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=128, verbose_name='описание')),
                ('call_name', models.CharField(blank=True, max_length=128, verbose_name='обращение')),
                ('phone', models.CharField(blank=True, max_length=128, verbose_name='телефон')),
                ('email', models.EmailField(blank=True, max_length=128, verbose_name='электронная почта')),
                ('position', models.SmallIntegerField(blank=True, null=True, verbose_name='позиция')),
                ('sug_company_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='companies.CompanyDraft')),
            ],
            options={
                'verbose_name': 'контакт',
                'ordering': ('position',),
                'verbose_name_plural': 'контакты',
                'abstract': False,
            },
        ),
    ]
