# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-04 04:37
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_auto_20170228_1043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='создатель профиля'),
        ),
        migrations.AlterField(
            model_name='companydraft',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='создатель черновика'),
        ),
    ]
