# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-09 05:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0004_pubemail_pubphone_sugemail_sugphone'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pubemail',
            options={'verbose_name': 'E-mail', 'verbose_name_plural': 'E-mail`ы'},
        ),
        migrations.AlterModelOptions(
            name='pubphone',
            options={'verbose_name': 'телефон', 'verbose_name_plural': 'телефоны'},
        ),
        migrations.AlterModelOptions(
            name='sugemail',
            options={'verbose_name': 'E-mail', 'verbose_name_plural': 'E-mail`ы'},
        ),
        migrations.AlterModelOptions(
            name='sugphone',
            options={'verbose_name': 'телефон', 'verbose_name_plural': 'телефоны'},
        ),
        migrations.AddField(
            model_name='pubemail',
            name='position',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='позиция'),
        ),
        migrations.AddField(
            model_name='pubphone',
            name='position',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='позиция'),
        ),
        migrations.AddField(
            model_name='sugemail',
            name='position',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='позиция'),
        ),
        migrations.AddField(
            model_name='sugphone',
            name='position',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='позиция'),
        ),
    ]
