# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-09 05:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0005_auto_20170709_0845'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pubemail',
            options={'ordering': ('position',), 'verbose_name': 'E-mail', 'verbose_name_plural': 'E-mail`ы'},
        ),
        migrations.AlterModelOptions(
            name='pubphone',
            options={'ordering': ('position',), 'verbose_name': 'телефон', 'verbose_name_plural': 'телефоны'},
        ),
        migrations.AlterModelOptions(
            name='sugemail',
            options={'ordering': ('position',), 'verbose_name': 'E-mail', 'verbose_name_plural': 'E-mail`ы'},
        ),
        migrations.AlterModelOptions(
            name='sugphone',
            options={'ordering': ('position',), 'verbose_name': 'телефон', 'verbose_name_plural': 'телефоны'},
        ),
        migrations.AddField(
            model_name='pubemail',
            name='info',
            field=models.CharField(blank=True, max_length=128, verbose_name='дополнительная информация'),
        ),
        migrations.AddField(
            model_name='pubphone',
            name='info',
            field=models.CharField(blank=True, max_length=128, verbose_name='дополнительная информация'),
        ),
        migrations.AddField(
            model_name='sugemail',
            name='info',
            field=models.CharField(blank=True, max_length=128, verbose_name='дополнительная информация'),
        ),
        migrations.AddField(
            model_name='sugphone',
            name='info',
            field=models.CharField(blank=True, max_length=128, verbose_name='дополнительная информация'),
        ),
    ]
