# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-09 06:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0006_auto_20170709_0851'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pubemail',
            old_name='info',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='pubphone',
            old_name='info',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='sugemail',
            old_name='info',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='sugphone',
            old_name='info',
            new_name='description',
        ),
    ]
