# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-09 06:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0007_auto_20170709_0905'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pubcompcontact',
            name='call_name',
        ),
        migrations.RemoveField(
            model_name='sugcompcontact',
            name='call_name',
        ),
        migrations.AddField(
            model_name='pubcompcontact',
            name='address',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='адрес'),
        ),
        migrations.AddField(
            model_name='sugcompcontact',
            name='address',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='адрес'),
        ),
    ]
