# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-09 06:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0010_auto_20170709_0941'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pubcompcontact',
            name='email',
        ),
        migrations.RemoveField(
            model_name='pubcompcontact',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='sugcompcontact',
            name='email',
        ),
        migrations.RemoveField(
            model_name='sugcompcontact',
            name='phone',
        ),
    ]
