# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-05 02:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0004_auto_20170304_0737'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='addraft',
            options={'ordering': ('is_published', '-is_ready', 'pk'), 'verbose_name': 'черновик', 'verbose_name_plural': 'черновики'},
        ),
        migrations.RemoveField(
            model_name='addraft',
            name='last_modified',
        ),
    ]
